/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boundary;

import control.Control;
import entity.Opgave;
import java.util.Collection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bobbie
 */
public class GUI extends javax.swing.JFrame {
    Control c;
    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        c = new Control();
        setUpTableBestilling();
    }

    private void setUpTableBestilling (){
        Collection<Opgave> opgaver = c.getAllOpgave();
        DefaultTableModel model = (DefaultTableModel) jTableBestillinger.getModel();
        model.setRowCount(0);
        
        for (Opgave opg : opgaver) {
            String dato = "";
            String by = "";
            String lokal = "";
            
            dato = opg.getStartDatoTid().toString();
            try {
                by = opg.getPostnr().toString();
            } catch (Exception e) {
            }

            lokal = opg.getLokal();
            Boolean bevilling = opg.getBevillingsnummer() != null;
            int tolke = opg.getTolkCollection().size();
            
            Object[] row = {dato, by, lokal, bevilling, tolke};
            model.addRow(row);
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanelBestillinger = new javax.swing.JPanel();
        jScrollPaneBestillinger = new javax.swing.JScrollPane();
        jTableBestillinger = new javax.swing.JTable();
        jPanelBrugere = new javax.swing.JPanel();
        jPanelTolke = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tolke Administration");

        jLabel2.setText("Velkommen");

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addComponent(jLabel2)))
                .addContainerGap(323, Short.MAX_VALUE))
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(399, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hovedside", jPanelMain);

        jTableBestillinger.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Dato", "By", "Lokal", "Bevilling", "Tolke"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBestillinger.setColumnSelectionAllowed(true);
        jScrollPaneBestillinger.setViewportView(jTableBestillinger);
        jTableBestillinger.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        javax.swing.GroupLayout jPanelBestillingerLayout = new javax.swing.GroupLayout(jPanelBestillinger);
        jPanelBestillinger.setLayout(jPanelBestillingerLayout);
        jPanelBestillingerLayout.setHorizontalGroup(
            jPanelBestillingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPaneBestillinger, javax.swing.GroupLayout.DEFAULT_SIZE, 669, Short.MAX_VALUE)
        );
        jPanelBestillingerLayout.setVerticalGroup(
            jPanelBestillingerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBestillingerLayout.createSequentialGroup()
                .addComponent(jScrollPaneBestillinger, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 167, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bestillinger", jPanelBestillinger);

        javax.swing.GroupLayout jPanelBrugereLayout = new javax.swing.GroupLayout(jPanelBrugere);
        jPanelBrugere.setLayout(jPanelBrugereLayout);
        jPanelBrugereLayout.setHorizontalGroup(
            jPanelBrugereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanelBrugereLayout.setVerticalGroup(
            jPanelBrugereLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Brugere", jPanelBrugere);

        javax.swing.GroupLayout jPanelTolkeLayout = new javax.swing.GroupLayout(jPanelTolke);
        jPanelTolke.setLayout(jPanelTolkeLayout);
        jPanelTolkeLayout.setHorizontalGroup(
            jPanelTolkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );
        jPanelTolkeLayout.setVerticalGroup(
            jPanelTolkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 456, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Tolke", jPanelTolke);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelBestillinger;
    private javax.swing.JPanel jPanelBrugere;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTolke;
    private javax.swing.JScrollPane jScrollPaneBestillinger;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableBestillinger;
    // End of variables declaration//GEN-END:variables
}
